name: "Run tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create virtual environment
        run: make venv

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make coverage
